function pug_rethrow(n,e,r,t){if(!(n instanceof Error))throw n;if(!("undefined"==typeof window&&e||t))throw n.message+=" on line "+r,n;try{t=t||require("fs").readFileSync(e,"utf8")}catch(e){pug_rethrow(n,null,r)}var i=3,a=t.split("\n"),o=Math.max(r-i,0),h=Math.min(a.length,r+i),i=a.slice(o,h).map(function(n,e){var t=e+o+1;return(t==r?"  > ":"    ")+t+"| "+n}).join("\n");throw n.path=e,n.message=(e||"Pug")+":"+r+"\n"+i+"\n\n"+n.message,n}function template(locals) {var pug_html = "", pug_mixins = {}, pug_interp;var pug_debug_filename, pug_debug_line;try {var pug_debug_sources = {"index.pug":"\u003C!DOCTYPE html\u003E\nhtml(lang=\"en\")\n\n\thead\n\n\t\tmeta(charset=\"UTF-8\")\n\t\tmeta(name=\"viewport\", content=\"width=device-width, initial-scale=1.0\")\n\t\tmeta(http-equiv=\"X-UA-Compatible\", content=\"ie=edge\")\n\n\t\tlink(rel=\"stylesheet\", href=\"style.css\")\n\n\t\ttitle Trivia | Game\n\n\tbody\n\n\t\t.container\n\n\t\t\t#title\n\n\t\t\t.question#question1\n\t\t\t.question#question2\n\t\t\t.question#question3\n\t\t\t.question#question4\n\n\t\tscript(src=\"\u002FAssets\u002FJavaScript\u002Fapp.js\")"};
;pug_debug_line = 1;pug_debug_filename = "index.pug";
pug_html = pug_html + "\u003C!DOCTYPE html\u003E";
;pug_debug_line = 2;pug_debug_filename = "index.pug";
pug_html = pug_html + "\u003Chtml lang=\"en\"\u003E";
;pug_debug_line = 4;pug_debug_filename = "index.pug";
pug_html = pug_html + "\u003Chead\u003E";
;pug_debug_line = 6;pug_debug_filename = "index.pug";
pug_html = pug_html + "\u003Cmeta charset=\"UTF-8\"\u002F\u003E";
;pug_debug_line = 7;pug_debug_filename = "index.pug";
pug_html = pug_html + "\u003Cmeta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"\u002F\u003E";
;pug_debug_line = 8;pug_debug_filename = "index.pug";
pug_html = pug_html + "\u003Cmeta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\"\u002F\u003E";
;pug_debug_line = 10;pug_debug_filename = "index.pug";
pug_html = pug_html + "\u003Clink rel=\"stylesheet\" href=\"style.css\"\u002F\u003E";
;pug_debug_line = 12;pug_debug_filename = "index.pug";
pug_html = pug_html + "\u003Ctitle\u003E";
;pug_debug_line = 12;pug_debug_filename = "index.pug";
pug_html = pug_html + "Trivia | Game\u003C\u002Ftitle\u003E\u003C\u002Fhead\u003E";
;pug_debug_line = 14;pug_debug_filename = "index.pug";
pug_html = pug_html + "\u003Cbody\u003E";
;pug_debug_line = 16;pug_debug_filename = "index.pug";
pug_html = pug_html + "\u003Cdiv class=\"container\"\u003E";
;pug_debug_line = 18;pug_debug_filename = "index.pug";
pug_html = pug_html + "\u003Cdiv id=\"title\"\u003E\u003C\u002Fdiv\u003E";
;pug_debug_line = 20;pug_debug_filename = "index.pug";
pug_html = pug_html + "\u003Cdiv class=\"question\" id=\"question1\"\u003E\u003C\u002Fdiv\u003E";
;pug_debug_line = 21;pug_debug_filename = "index.pug";
pug_html = pug_html + "\u003Cdiv class=\"question\" id=\"question2\"\u003E\u003C\u002Fdiv\u003E";
;pug_debug_line = 22;pug_debug_filename = "index.pug";
pug_html = pug_html + "\u003Cdiv class=\"question\" id=\"question3\"\u003E\u003C\u002Fdiv\u003E";
;pug_debug_line = 23;pug_debug_filename = "index.pug";
pug_html = pug_html + "\u003Cdiv class=\"question\" id=\"question4\"\u003E\u003C\u002Fdiv\u003E\u003C\u002Fdiv\u003E";
;pug_debug_line = 25;pug_debug_filename = "index.pug";
pug_html = pug_html + "\u003Cscript src=\"\u002FAssets\u002FJavaScript\u002Fapp.js\"\u003E\u003C\u002Fscript\u003E\u003C\u002Fbody\u003E\u003C\u002Fhtml\u003E";} catch (err) {pug_rethrow(err, pug_debug_filename, pug_debug_line, pug_debug_sources[pug_debug_filename]);};return pug_html;}